In [1]:
# ICMA Task
# Author : Adeel Feroz (TechmaZone Batch 10)
# Filename : Data Comparision
# 17th - July22 4:40

In [154]:
import pandas as pd

In [155]:
data = pd.read_excel("Data Comparision.xlsx",'Climax')

In [156]:
oldRecords = data.iloc[:41,:2]
newRecords = data.iloc[:48,4:]

In [157]:
oldRecords.columns = oldRecords.iloc[0]
newRecords.columns = newRecords.iloc[0]

In [158]:
oldRecords = oldRecords[1:]
newRecords = newRecords[1:]

In [159]:
oldRecords["Client Name"] = oldRecords["Client Name"].str.replace("\(EXPORT\)","")
oldRecords["Client Name"] = oldRecords["Client Name"].str.strip()
oldRecords

/tmp/ipykernel_400955/2731138404.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  oldRecords["Client Name"] = oldRecords["Client Name"].str.replace("\(EXPORT\)","")

0                           Client Name   Balance
1              ABDUR RAHMAN CORPORATION     93073
2                  AL HARAM ENTERPRISES    879466
3                     AL MAKKAH EXPORTS    938307
4                 AL SHEIKH ENTERPRISES      7500
5                 ALLAH TAWAKAL TEXTILE   1828863
6                   ASIATEX CORPORATION   2296736
7                           ASK TEXTILE   1113103
8                BEACON IMPEX (PVT) LTD     75043
9            CAROLINA FABRICS (PVT) LTD   5425170
10                COTTON EMPIRE PVT LTD       100
11                         DECORA IMPEX   1489000
12                    DOCUMENT SOLUTION     41000
13           FACILITIES SHIPPING AGENCY      2000
14                     FALCON LOGISTICS      8468
15                      HANZALA TRADERS    261900
16                       I & U AGENCIES    207810
17                   IMPO-INTERNATIONAL     76950
18                        KALIM TEXTILE    393996
19       MAHEEN TEXTILE MILLS (PVT) LTD     67085
20                  MANZA TEXTILE MILLS     -3180
21             MASOOD TEXTILE MILLS LTD    142709
22                          MN CHEMICAL    945200
23                     NB INTERNATIONAL  70270.11
24                 NISHAT MILLS LIMITED     16000
25                      PAKISTAN FIBRES      6461
26     PAKISTAN INDUSTRIAL AIDS PVT LTD     12000
27                ROOMI FABRICS LIMITED   2749617
28                   ROOMI HOME PVT LTD   1373758
29             SACHIN SPORTS INDUSTRIES      6500
30          SANI SHIPPING AND LOGISTICS     83130
31              SERVICE INDUSTRIES LTD.      1461
32               SNA TEXTILES (PVT) LTD  14671256
33      SULTANI ELASTO PRODUCTS PVT LTD  14514719
34                  SUN FIBER (PVT) LTD     83575
35      SUPPLY CHAIN LOGISTICS SERVICES   1956045
36                 TEHAMI INTERNATIONAL   2989986
37      UNICON INTERNATIONAL (PVT.) LTD    670726
38                  UNLIMITED LOGISTICS   4147572
39  VISION TECHNOLOGIES CORPORATION (PR      2500
40          ZAHIDJEE TEXTILES MILLS LTD     16671

In [160]:
newRecords["Client Name"] = newRecords['Client Name'].str.replace("\(EXPORT\)","")
newRecords["Client Name"] = newRecords['Client Name'].str.strip()
newRecords

/tmp/ipykernel_400955/45624249.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  newRecords["Client Name"] = newRecords['Client Name'].str.replace("\(EXPORT\)","")

0                           Client Name   Balance
1                  AB EXPORTS (PVT) LTD     16644
2              ABDUR RAHMAN CORPORATION     93073
3                  AL HARAM ENTERPRISES    879466
4                     AL MAKKAH EXPORTS    938307
5                 AL SHEIKH ENTERPRISES      7500
6                 ALLAH TAWAKAL TEXTILE   1828863
7                         ARSA KNITWARE   1584920
8           ARZOO TEXTILE MILLS LIMITED   1956045
9                   ASIATEX CORPORATION    784182
10                          ASK TEXTILE   1113103
11               BEACON IMPEX (PVT) LTD     75043
12           CAROLINA FABRICS (PVT) LTD   5425170
13                COTTON EMPIRE PVT LTD       100
14                         DECORA IMPEX   1489000
15                    DREAMTEX INDUSTRY    946501
16           FACILITIES SHIPPING AGENCY      2000
17                   FAISAL FABRICS LTD      9485
18                     FALCON LOGISTICS      8468
19           GLOBELINK PAKISTAN PVT LTD     67156
20                      HANZALA TRADERS    261900
21                           HM TRADERS     41000
22                   IMPO-INTERNATIONAL     76950
23                 JAVED GLOVES PVT LTD   3031445
24                        KALIM TEXTILE    393996
25                       KB ENTERPRISES     27310
26       MAHEEN TEXTILE MILLS (PVT) LTD     67085
27             MASOOD TEXTILE MILLS LTD    142709
28                          MN CHEMICAL    945200
29                     NB INTERNATIONAL  70729.11
30                 NISHAT MILLS LIMITED     16000
31                      PAKISTAN FIBRES      6461
32     PAKISTAN INDUSTRIAL AIDS PVT LTD     12000
33                ROOMI FABRICS LIMITED   4123375
34             SACHIN SPORTS INDUSTRIES      6500
35                        SAGAR HOISERY   1616151
36          SANI SHIPPING AND LOGISTICS     83130
37              SERVICE INDUSTRIES LTD.      1461
38               SGS PAKISTAN (PVT) LTD    207810
39               SNA TEXTILES (PVT) LTD  14687456
40      SULTANI ELASTO PRODUCTS PVT LTD  14514719
41                  SUN FIBER (PVT) LTD     83575
42      UNICON INTERNATIONAL (PVT.) LTD    670726
43                  UNLIMITED LOGISTICS   4147572
44  VISION TECHNOLOGIES CORPORATION (PR      2500
45         WATERLINK PAKISTAN (PVT) LTD     38430
46                    ZAHID JEE TEXTILE     17331
47          ZAHIDJEE TEXTILES MILLS LTD     16671

In [161]:
mergedDF = pd.merge(oldRecords,newRecords,how = "outer",on = "Client Name",suffixes=("_Old","_New"))

In [162]:
mergedDF["Nominal"] = ""

In [163]:
for i in range(len(mergedDF)):
    if str(mergedDF.iloc[i,1])=="nan":
        mergedDF.iloc[i,3] = "Missing Old"
        continue
    if str(mergedDF.iloc[i,2]) == "nan":
        mergedDF.iloc[i,3] = "Missing New"
        continue
    if mergedDF.iloc[i,1] == mergedDF.iloc[i,2]:
        mergedDF.iloc[i,3] = "Matched"
        continue
    mergedDF.iloc[i,3] = "Not Matched"

In [164]:
mergedDF = mergedDF.sort_values("Client Name").reset_index(drop=True)
mergedDF

0                           Client Name Balance_Old Balance_New      Nominal
0                  AB EXPORTS (PVT) LTD         NaN       16644  Missing Old
1              ABDUR RAHMAN CORPORATION       93073       93073      Matched
2                  AL HARAM ENTERPRISES      879466      879466      Matched
3                     AL MAKKAH EXPORTS      938307      938307      Matched
4                 AL SHEIKH ENTERPRISES        7500        7500      Matched
5                 ALLAH TAWAKAL TEXTILE     1828863     1828863      Matched
6                         ARSA KNITWARE         NaN     1584920  Missing Old
7           ARZOO TEXTILE MILLS LIMITED         NaN     1956045  Missing Old
8                   ASIATEX CORPORATION     2296736      784182  Not Matched
9                           ASK TEXTILE     1113103     1113103      Matched
10               BEACON IMPEX (PVT) LTD       75043       75043      Matched
11           CAROLINA FABRICS (PVT) LTD     5425170     5425170      Matched
12                COTTON EMPIRE PVT LTD         100         100      Matched
13                         DECORA IMPEX     1489000     1489000      Matched
14                    DOCUMENT SOLUTION       41000         NaN  Missing New
15                    DREAMTEX INDUSTRY         NaN      946501  Missing Old
16           FACILITIES SHIPPING AGENCY        2000        2000      Matched
17                   FAISAL FABRICS LTD         NaN        9485  Missing Old
18                     FALCON LOGISTICS        8468        8468      Matched
19           GLOBELINK PAKISTAN PVT LTD         NaN       67156  Missing Old
20                      HANZALA TRADERS      261900      261900      Matched
21                           HM TRADERS         NaN       41000  Missing Old
22                       I & U AGENCIES      207810         NaN  Missing New
23                   IMPO-INTERNATIONAL       76950       76950      Matched
24                 JAVED GLOVES PVT LTD         NaN     3031445  Missing Old
25                        KALIM TEXTILE      393996      393996      Matched
26                       KB ENTERPRISES         NaN       27310  Missing Old
27       MAHEEN TEXTILE MILLS (PVT) LTD       67085       67085      Matched
28                  MANZA TEXTILE MILLS       -3180         NaN  Missing New
29             MASOOD TEXTILE MILLS LTD      142709      142709      Matched
30                          MN CHEMICAL      945200      945200      Matched
31                     NB INTERNATIONAL    70270.11    70729.11  Not Matched
32                 NISHAT MILLS LIMITED       16000       16000      Matched
33                      PAKISTAN FIBRES        6461        6461      Matched
34     PAKISTAN INDUSTRIAL AIDS PVT LTD       12000       12000      Matched
35                ROOMI FABRICS LIMITED     2749617     4123375  Not Matched
36                   ROOMI HOME PVT LTD     1373758         NaN  Missing New
37             SACHIN SPORTS INDUSTRIES        6500        6500      Matched
38                        SAGAR HOISERY         NaN     1616151  Missing Old
39          SANI SHIPPING AND LOGISTICS       83130       83130      Matched
40              SERVICE INDUSTRIES LTD.        1461        1461      Matched
41               SGS PAKISTAN (PVT) LTD         NaN      207810  Missing Old
42               SNA TEXTILES (PVT) LTD    14671256    14687456  Not Matched
43      SULTANI ELASTO PRODUCTS PVT LTD    14514719    14514719      Matched
44                  SUN FIBER (PVT) LTD       83575       83575      Matched
45      SUPPLY CHAIN LOGISTICS SERVICES     1956045         NaN  Missing New
46                 TEHAMI INTERNATIONAL     2989986         NaN  Missing New
47      UNICON INTERNATIONAL (PVT.) LTD      670726      670726      Matched
48                  UNLIMITED LOGISTICS     4147572     4147572      Matched
49  VISION TECHNOLOGIES CORPORATION (PR        2500        2500      Matched
50         WATERLINK PAKISTAN (PVT) LTD         NaN       38430  Missing Old
51                    ZAHID JEE TEXTILE         NaN       17331  Missing Old
52          ZAHIDJEE TEXTILES MILLS LTD       16671       16671      Matched

In [165]:
mergedDF.to_excel("Combined DataFrame.xlsx",index=False)