In [ ]:
# Data Analysis Exam
# Jun 26 2022
# Code By: Adeel Feroz
# Techmazone B-10

In [83]:
import re
import pandas as pd
import calendar
from openpyxl import load_workbook

In [2]:
df = pd.read_excel("Account Data Cleaned.xlsx")

In [3]:
df

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC)
0,7100,UNIT17 REFURBISHMENT,2021-01-01,200-139439,Open21b,NaN,7100,NaN,GBP,132766.54,0.0,132766.54,0.0,132766.54,0.0
1,7101,BLDG FIXT & FITTINGS,2021-01-01,200-139439,Open21b,NaN,7101,NaN,GBP,76150.00,0.0,76150.00,0.0,76150.00,0.0
2,7102,PLANT & MACHINERY,2021-01-01,200-139439,Open21b,NaN,7102,NaN,GBP,33778.97,0.0,33778.97,0.0,33778.97,0.0
3,7102,PLANT & MACHINERY,2021-04-30,200-139742,GLV150007723,Ledger journal,7102,APIIN018911 - Low ohm meter - RS Components - ...,GBP,2399.00,0.0,2399.00,0.0,2399.00,0.0
4,7103,OFFICE EQUIPMENT,2021-01-01,200-139439,Open21b,NaN,7103,NaN,GBP,14591.18,0.0,14591.18,0.0,14591.18,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88562,6111,ELMA TRADEMARK FEE,2021-06-30,200-142157,GLV150007843,Ledger journal,6111-10800,Accruals June 2021,GBP,4830.00,0.0,4830.00,0.0,4830.00,0.0
88563,6111,ELMA TRADEMARK FEE,2021-07-31,200-144352,GLV150007912,Ledger journal,6111-10800,Trade mark fee July,GBP,2100.00,0.0,2100.00,0.0,2100.00,0.0
88564,6111,ELMA TRADEMARK FEE,2021-08-31,200-146400,GLV150007974,Ledger journal,6111-10800,Accruals August,GBP,5270.00,0.0,5270.00,0.0,5270.00,0.0
88565,6111,ELMA TRADEMARK FEE,2021-09-30,200-147849,GLV150008017,Ledger journal,6111-10800,Accruals movement Sep,GBP,2780.00,0.0,2780.00,0.0,2780.00,0.0
88566,6111,ELMA TRADEMARK FEE,2021-10-31,200-149364,GLV150008081,Ledger journal,6111-10800,Accruals Oct 2021,GBP,6152.00,0.0,6152.00,0.0,6152.00,0.0

In [4]:
df["Amount"] = df["Debit (AC)"] - df["Credit (RC)"]

In [5]:
df.head(15)

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC),Amount
0,7100,UNIT17 REFURBISHMENT,2021-01-01,200-139439,Open21b,NaN,7100,NaN,GBP,132766.54,0.00,132766.54,0.00,132766.54,0.00,132766.54
1,7101,BLDG FIXT & FITTINGS,2021-01-01,200-139439,Open21b,NaN,7101,NaN,GBP,76150.00,0.00,76150.00,0.00,76150.00,0.00,76150.00
2,7102,PLANT & MACHINERY,2021-01-01,200-139439,Open21b,NaN,7102,NaN,GBP,33778.97,0.00,33778.97,0.00,33778.97,0.00,33778.97
3,7102,PLANT & MACHINERY,2021-04-30,200-139742,GLV150007723,Ledger journal,7102,APIIN018911 - Low ohm meter - RS Components - ...,GBP,2399.00,0.00,2399.00,0.00,2399.00,0.00,2399.00
4,7103,OFFICE EQUIPMENT,2021-01-01,200-139439,Open21b,NaN,7103,NaN,GBP,14591.18,0.00,14591.18,0.00,14591.18,0.00,14591.18
5,7104,COMPUTER EQUIPMENT,2021-01-01,200-139439,Open21b,NaN,7104,NaN,GBP,199765.63,0.00,199765.63,0.00,199765.63,0.00,199765.63
6,7104,COMPUTER EQUIPMENT,2021-01-01,200-139439,Open21b,NaN,7104,NaN,USD,67867.09,0.00,45363.80,0.00,45363.80,0.00,45363.80
7,7104,COMPUTER EQUIPMENT,2021-02-24,200-137353,200-000005252,Ledger journal,7104,Amanda Littley computer equipment,GBP,2252.80,0.00,2252.80,0.00,2252.80,0.00,2252.80
8,7105,MOTOR VEHICLES,2021-01-01,200-139439,Open21b,NaN,7105,NaN,GBP,23313.48,0.00,23313.48,0.00,23313.48,0.00,23313.48
9,7105,MOTOR VEHICLES,2021-04-30,200-139696,GLV150007710,Ledger journal,7105,Sale of car,GBP,0.00,23313.48,0.00,23313.48,0.00,23313.48,-23313.48
10,7109,IT LICENCES,2021-01-01,200-139439,Open21b,NaN,7109,NaN,GBP,14253.33,0.00,14253.33,0.00,14253.33,0.00,14253.33
11,7150,ACCUM DEPN IT LICENCES,2021-01-01,200-139439,Open21b,NaN,7150,NaN,GBP,0.00,14253.33,0.00,14253.33,0.00,14253.33,-14253.33
12,7200,ACCUM DEPN UNIT 17 REFURBISHMENT,2021-01-01,200-139439,Open21b,NaN,7200,NaN,GBP,0.00,100955.10,0.00,100955.10,0.00,100955.10,-100955.10
13,7200,ACCUM DEPN UNIT 17 REFURBISHMENT,2021-01-29,200-136501,GLV150007511,Ledger journal,7200,Fixed Assets January 2021,GBP,0.00,348.00,0.00,348.00,0.00,348.00,-348.00
14,7200,ACCUM DEPN UNIT 17 REFURBISHMENT,2021-02-28,200-137508,GLV150007596,Ledger journal,7200,Fixed asset Depn Feb 21,GBP,0.00,348.00,0.00,348.00,0.00,348.00,-348.00

In [6]:
pattern = "(999|000).?0*$"
text = "0.00"
print(re.search(pattern,text))

None

In [7]:
df["Amount"] = df["Amount"].astype(str)

In [8]:
df[df["Amount"].str.contains(pattern)].sort_values("Amount")

/tmp/ipykernel_6825/3059575444.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df["Amount"].str.contains(pattern)].sort_values("Amount")

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC),Amount
13177,8100,INVENTORY,2021-02-24,200-137299,PRCV004305,"Production, report as finished",8100-SYS_Comp-Systems-MS219261,NaN,GBP,0.0,1000.0,0.0,1000.0,0.0,1000.0,-1000.0
88177,5501,AUDIT FEES,2021-02-28,200-137713,GLV150007620,Ledger journal,5501-10800,Release corp tax accrual,GBP,0.0,1000.0,0.0,1000.0,0.0,1000.0,-1000.0
79626,1000,SALES,2021-05-24,200-140595,200-180008385,Project - invoiced revenue,1000-GB-Ind Aut-SYS_Comp-Systems-NRE,NaN,GBP,0.0,1000.0,0.0,1000.0,0.0,1000.0,-1000.0
66114,9201,SUNDRY CREDITORS & ACCRUALS,2021-02-28,200-137706,GLV150007616,Ledger journal,9201,Water accrual Feb 21,GBP,0.0,1000.0,0.0,1000.0,0.0,1000.0,-1000.0
66099,9201,SUNDRY CREDITORS & ACCRUALS,2021-01-31,200-136739,GLV150007539,Ledger journal,9201,Water Accrual - Jan,GBP,0.0,1000.0,0.0,1000.0,0.0,1000.0,-1000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58326,8525,BARCLAYS GBP ACCOUNT,2021-03-09,200-137897,CPAYM003869,Bank,8525,Proforma,GBP,6000.0,0.0,6000.0,0.0,6000.0,0.0,6000.0
82297,2000,MATERIAL COST OF SALES,2021-07-05,200-142390,APIIN019434,"Purchase, stock receipt",2000-10200---SYS_Comp-Systems-NON-STOCK ITEM,Supplier invoice,GBP,7000.0,0.0,7000.0,0.0,7000.0,0.0,7000.0
5490,8100,INVENTORY,2021-01-01,200-139439,Open21b,NaN,8100-Rotary Switches-RS-BV22870,NaN,GBP,9000.0,0.0,9000.0,0.0,9000.0,0.0,9000.0
81767,2000,MATERIAL COST OF SALES,2021-05-19,200-140448,APIIN019118,"Purchase, stock receipt",2000-10000---SYS_Comp-Systems-NON-STOCK ITEM,Supplier invoice,GBP,999.0,0.0,999.0,0.0,999.0,0.0,999.0
84440,2103,SMALL TOOLS/EQUIPMENT,2021-05-31,200-140923,GLV150007786,Ledger journal,2103------,Soldering stations x3 APIIN019118,GBP,999.0,0.0,999.0,0.0,999.0,0.0,999.0

In [9]:
holidays = ["01-Jan","10-Apr","13-Apr","04-May","25-May","31-Aug","25-Dec","28-Dec"]

In [18]:
from datetime import datetime

In [85]:
SaturdayDF = pd.read_excel("SaturdayDF.xlsx")
SundayDF = pd.read_excel("SundayDF.xlsx")
HolidayDF = pd.read_excel("HolidayDF.xlsx")
for idx,i in enumerate(df["Date"]):
    if i.strftime("%A") == "Saturday":
        SaturdayDF = SaturdayDF.append(df.iloc[idx])
    if i.strftime("%A") == "Sunday":
        SundayDF = SundayDF.append(df.iloc[idx])
    day = i.strftime("%d")
    month = i.strftime("%b")
    hol = day + "-" + month
    if hol in holidays:
        HolidayDF = HolidayDF.append(df.iloc[idx])

In [86]:
WeekendHolidaysDF = pd.DataFrame(columns= df.columns)
WeekendHolidaysDF = WeekendHolidaysDF.append(SaturdayDF)
WeekendHolidaysDF = WeekendHolidaysDF.append(SundayDF)
WeekendHolidaysDF = WeekendHolidaysDF.append(HolidayDF)

/tmp/ipykernel_6825/2103812433.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  WeekendHolidaysDF = WeekendHolidaysDF.append(SaturdayDF)
/tmp/ipykernel_6825/2103812433.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  WeekendHolidaysDF = WeekendHolidaysDF.append(SundayDF)
/tmp/ipykernel_6825/2103812433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  WeekendHolidaysDF = WeekendHolidaysDF.append(HolidayDF)

In [87]:
WeekendHolidaysDF.reset_index(drop = True, inplace = True)

In [88]:
writer = pd.ExcelWriter("Analysis.xlsx",engine="xlsxwriter")
WeekendHolidaysDF.to_excel(writer, sheet_name= "WeekendHolidays", index=False)
df[df["Amount"].str.contains(pattern)].sort_values("Amount").to_excel(writer,index = False, sheet_name = "Amount")
writer.save()
writer.close()

/tmp/ipykernel_6825/2635476890.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df["Amount"].str.contains(pattern)].sort_values("Amount").to_excel(writer,index = False, sheet_name = "Amount")
/home/adeel/anaconda3/lib/python3.9/site-packages/xlsxwriter/workbook.py:338: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [11]:
df

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC),Amount
0,7100,UNIT17 REFURBISHMENT,2021-01-01,200-139439,Open21b,NaN,7100,NaN,GBP,132766.54,0.0,132766.54,0.0,132766.54,0.0,132766.54
1,7101,BLDG FIXT & FITTINGS,2021-01-01,200-139439,Open21b,NaN,7101,NaN,GBP,76150.00,0.0,76150.00,0.0,76150.00,0.0,76150.0
2,7102,PLANT & MACHINERY,2021-01-01,200-139439,Open21b,NaN,7102,NaN,GBP,33778.97,0.0,33778.97,0.0,33778.97,0.0,33778.97
3,7102,PLANT & MACHINERY,2021-04-30,200-139742,GLV150007723,Ledger journal,7102,APIIN018911 - Low ohm meter - RS Components - ...,GBP,2399.00,0.0,2399.00,0.0,2399.00,0.0,2399.0
4,7103,OFFICE EQUIPMENT,2021-01-01,200-139439,Open21b,NaN,7103,NaN,GBP,14591.18,0.0,14591.18,0.0,14591.18,0.0,14591.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88562,6111,ELMA TRADEMARK FEE,2021-06-30,200-142157,GLV150007843,Ledger journal,6111-10800,Accruals June 2021,GBP,4830.00,0.0,4830.00,0.0,4830.00,0.0,4830.0
88563,6111,ELMA TRADEMARK FEE,2021-07-31,200-144352,GLV150007912,Ledger journal,6111-10800,Trade mark fee July,GBP,2100.00,0.0,2100.00,0.0,2100.00,0.0,2100.0
88564,6111,ELMA TRADEMARK FEE,2021-08-31,200-146400,GLV150007974,Ledger journal,6111-10800,Accruals August,GBP,5270.00,0.0,5270.00,0.0,5270.00,0.0,5270.0
88565,6111,ELMA TRADEMARK FEE,2021-09-30,200-147849,GLV150008017,Ledger journal,6111-10800,Accruals movement Sep,GBP,2780.00,0.0,2780.00,0.0,2780.00,0.0,2780.0
88566,6111,ELMA TRADEMARK FEE,2021-10-31,200-149364,GLV150008081,Ledger journal,6111-10800,Accruals Oct 2021,GBP,6152.00,0.0,6152.00,0.0,6152.00,0.0,6152.0

In [53]:
AmountPerMo = df.groupby(df["Date"].dt.month)["Debit (AC)"].agg(["count","sum"])

In [75]:
AmountPerMo.reset_index(inplace = True)

In [81]:
AmountPerMo["Date"] = AmountPerMo["Date"].apply(lambda x: calendar.month_abbr[x])

In [90]:
AmountPerMo.columns = ["Month","Transactions","Transaction Amount"]

In [91]:
wb = load_workbook("Analysis.xlsx")
wr = pd.ExcelWriter("Analysis.xlsx", engine="openpyxl")
wr.book = wb
AmountPerMo.to_excel(wr,sheet_name="AmountPerMonth", index = False)
wr.save()
wr.close()

In [110]:
pattern = "(R|r)evers"
text = "Reversal"
print(re.match(pattern,text,flags=re.I))

<re.Match object; span=(0, 6), match='Revers'>

In [111]:
reversedJ = df[df["Description"].str.contains(pattern) == True]

/tmp/ipykernel_6825/3682523298.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  reversedJ = df[df["Description"].str.contains(pattern) == True]

In [112]:
wb = load_workbook("Analysis.xlsx")
wr = pd.ExcelWriter("Analysis.xlsx", engine="openpyxl")
wr.book = wb
reversedJ.to_excel(wr,sheet_name="Reversed Journal", index = False)
wr.save()
wr.close()

In [116]:
JournalNums = df["Journal number"].str.replace("200-","")

In [121]:
JournalNums = set(JournalNums)

In [123]:
JournalNums = list(sorted(JournalNums))

In [139]:
JournalNums[2]

'135703'

In [129]:
Gaps = [0]

In [130]:
for i in range(1,len(JournalNums)):
    Gaps.append(int(JournalNums[i])-int(JournalNums[i-1]))

In [135]:
Gaps[2]

40

In [141]:
GapsDF = pd.DataFrame(columns= ["Journal Number","Gap"])

In [142]:
GapsDF["Journal Number"] = JournalNums

In [143]:
GapsDF["Gap"] = Gaps

In [146]:
GapsDF = GapsDF[GapsDF["Gap"]>1]

In [147]:
wb = load_workbook("Analysis.xlsx")
wr = pd.ExcelWriter("Analysis.xlsx", engine="openpyxl")
wr.book = wb
GapsDF.to_excel(wr,sheet_name="Journal Gaps", index = False)
wr.save()
wr.close()

In [165]:
DebtTCS = df[(df["Account Number"]==1000) & (df["Debit (AC)"]>0)][["Account Number","Debit (AC)"]]

In [166]:
wb = load_workbook("Analysis.xlsx")
wr = pd.ExcelWriter("Analysis.xlsx", engine="openpyxl")
wr.book = wb
DebtTCS.to_excel(wr,sheet_name="Debit Transactions for 1000", index = False)
wr.save()
wr.close()

In [245]:
BankAcc = [8525,8526,8527,8528]
PreAcc = [8250]
AccrualAcc  = [9201,9202,9205,9206,9213]

In [246]:
BankVouchers = df[df["Account Number"].isin(BankAcc)]
BankVouchers = BankVouchers.groupby(["Account Number"])["Voucher"].agg("unique")
BankVouchers

Account Number
8525    [Open21b, CPAYM003780, CPAYM003781, CPAYM00378...
8526    [Open21b, VPAYM007359, GLV150007508, GLV150007...
8527    [Open21b, GLV150007520, GLV150007605, GLV15000...
8528    [Open21b, GLV150007519, GLV150007606, GLV15000...
Name: Voucher, dtype: object

In [247]:
PreVouchers = df[df["Account Number"].isin(PreAcc)]
PreVouchers = PreVouchers.groupby(["Account Number"])["Voucher"].agg("unique")
PreVouchers

Account Number
8250    [Open21b, 200-000005175, 200-000005200, GLV150...
Name: Voucher, dtype: object

In [249]:
AccrualVouchers = df[df["Account Number"].isin(AccrualAcc)]
AccrualVouchers = AccrualVouchers.groupby(["Account Number"])["Voucher"].agg("unique")
AccrualVouchers

Account Number
9201    [Open21b, GLV150007449, GLV150007450, GLV15000...
9202                                            [Open21b]
9205                                       [ARFTIV000126]
9206    [Open21b, GLV150007489, GLV150007490, GLV15000...
9213    [Open21b, GLV150007659, GLV150007737, GLV15000...
Name: Voucher, dtype: object

In [259]:
AllBankVouchers = set()
for i in BankVouchers:
    for j in i:
        AllBankVouchers.add(j)
AllBankVouchers = list(sorted(AllBankVouchers))
AllBankVouchers

['BCS000000180',
 'BCS000000182',
 'BCS000000183',
 'BCS000000184',
 'BCS000000186',
 'CPAYM003780',
 'CPAYM003781',
 'CPAYM003782',
 'CPAYM003783',
 'CPAYM003784',
 'CPAYM003785',
 'CPAYM003786',
 'CPAYM003787',
 'CPAYM003788',
 'CPAYM003789',
 'CPAYM003790',
 'CPAYM003791',
 'CPAYM003792',
 'CPAYM003793',
 'CPAYM003794',
 'CPAYM003795',
 'CPAYM003796',
 'CPAYM003797',
 'CPAYM003798',
 'CPAYM003799',
 'CPAYM003800',
 'CPAYM003801',
 'CPAYM003802',
 'CPAYM003803',
 'CPAYM003804',
 'CPAYM003805',
 'CPAYM003806',
 'CPAYM003807',
 'CPAYM003808',
 'CPAYM003809',
 'CPAYM003810',
 'CPAYM003811',
 'CPAYM003812',
 'CPAYM003813',
 'CPAYM003814',
 'CPAYM003815',
 'CPAYM003816',
 'CPAYM003817',
 'CPAYM003818',
 'CPAYM003819',
 'CPAYM003820',
 'CPAYM003821',
 'CPAYM003822',
 'CPAYM003823',
 'CPAYM003824',
 'CPAYM003825',
 'CPAYM003826',
 'CPAYM003827',
 'CPAYM003828',
 'CPAYM003829',
 'CPAYM003830',
 'CPAYM003831',
 'CPAYM003832',
 'CPAYM003833',
 'CPAYM003834',
 'CPAYM003835',
 'CPAYM003836',
 'CPAYM003837',
 'CPAYM003838',
 'CPAYM003839',
 'CPAYM003840',
 'CPAYM003841',
 'CPAYM003842',
 'CPAYM003843',
 'CPAYM003844',
 'CPAYM003845',
 'CPAYM003846',
 'CPAYM003847',
 'CPAYM003848',
 'CPAYM003849',
 'CPAYM003850',
 'CPAYM003851',
 'CPAYM003852',
 'CPAYM003853',
 'CPAYM003854',
 'CPAYM003855',
 'CPAYM003856',
 'CPAYM003857',
 'CPAYM003858',
 'CPAYM003859',
 'CPAYM003860',
 'CPAYM003861',
 'CPAYM003862',
 'CPAYM003863',
 'CPAYM003864',
 'CPAYM003865',
 'CPAYM003866',
 'CPAYM003867',
 'CPAYM003868',
 'CPAYM003869',
 'CPAYM003870',
 'CPAYM003871',
 'CPAYM003872',
 'CPAYM003873',
 'CPAYM003874',
 'CPAYM003875',
 'CPAYM003876',
 'CPAYM003877',
 'CPAYM003878',
 'CPAYM003879',
 'CPAYM003880',
 'CPAYM003881',
 'CPAYM003882',
 'CPAYM003883',
 'CPAYM003884',
 'CPAYM003885',
 'CPAYM003886',
 'CPAYM003887',
 'CPAYM003888',
 'CPAYM003889',
 'CPAYM003890',
 'CPAYM003891',
 'CPAYM003892',
 'CPAYM003893',
 'CPAYM003894',
 'CPAYM003895',
 'CPAYM003896',
 'CPAYM003897',
 'CPAYM003898',
 'CPAYM003899',
 'CPAYM003900',
 'CPAYM003901',
 'CPAYM003902',
 'CPAYM003903',
 'CPAYM003904',
 'CPAYM003905',
 'CPAYM003906',
 'CPAYM003907',
 'CPAYM003908',
 'CPAYM003909',
 'CPAYM003910',
 'CPAYM003911',
 'CPAYM003912',
 'CPAYM003913',
 'CPAYM003914',
 'CPAYM003915',
 'CPAYM003916',
 'CPAYM003917',
 'CPAYM003918',
 'CPAYM003919',
 'CPAYM003920',
 'CPAYM003921',
 'CPAYM003922',
 'CPAYM003923',
 'CPAYM003924',
 'CPAYM003925',
 'CPAYM003926',
 'CPAYM003927',
 'CPAYM003928',
 'CPAYM003929',
 'CPAYM003930',
 'CPAYM003931',
 'CPAYM003932',
 'CPAYM003933',
 'CPAYM003934',
 'CPAYM003935',
 'CPAYM003936',
 'CPAYM003937',
 'CPAYM003938',
 'CPAYM003939',
 'CPAYM003940',
 'CPAYM003941',
 'CPAYM003942',
 'CPAYM003943',
 'CPAYM003944',
 'CPAYM003945',
 'CPAYM003946',
 'CPAYM003947',
 'CPAYM003948',
 'CPAYM003949',
 'CPAYM003950',
 'CPAYM003951',
 'CPAYM003952',
 'CPAYM003953',
 'CPAYM003954',
 'CPAYM003955',
 'CPAYM003956',
 'CPAYM003957',
 'CPAYM003958',
 'CPAYM003959',
 'CPAYM003960',
 'CPAYM003961',
 'CPAYM003962',
 'CPAYM003963',
 'CPAYM003964',
 'CPAYM003965',
 'CPAYM003966',
 'CPAYM003967',
 'CPAYM003968',
 'CPAYM003969',
 'CPAYM003970',
 'CPAYM003971',
 'CPAYM003972',
 'CPAYM003973',
 'CPAYM003974',
 'CPAYM003975',
 'CPAYM003976',
 'CPAYM003977',
 'CPAYM003978',
 'CPAYM003979',
 'CPAYM003980',
 'CPAYM003981',
 'CPAYM003982',
 'CPAYM003983',
 'CPAYM003984',
 'CPAYM003985',
 'CPAYM003986',
 'CPAYM003987',
 'CPAYM003988',
 'CPAYM003989',
 'CPAYM003990',
 'CPAYM003991',
 'CPAYM003992',
 'CPAYM003993',
 'CPAYM003994',
 'CPAYM003995',
 'CPAYM003996',
 'CPAYM003997',
 'CPAYM003998',
 'CPAYM003999',
 'CPAYM004000',
 'CPAYM004001',
 'CPAYM004002',
 'CPAYM004003',
 'CPAYM004004',
 'CPAYM004005',
 'CPAYM004006',
 'CPAYM004007',
 'CPAYM004008',
 'CPAYM004009',
 'CPAYM004010',
 'CPAYM004011',
 'CPAYM004012',
 'CPAYM004013',
 'CPAYM004014',
 'CPAYM004015',
 'CPAYM004016',
 'CPAYM004017',
 'CPAYM004018',
 'CPAYM004019',
 'CPAYM004020',
 'CPAYM004021',
 'CPAYM004022',
 'CPAYM004023',
 'CPAYM004024',
 'CPAYM004025',
 'CPAYM004026',
 'CPAYM004027',
 'CPAYM004028',
 'CPAYM004029',
 'CPAYM004030',
 'CPAYM004031',
 'CPAYM004032',
 'CPAYM004033',
 'CPAYM004034',
 'CPAYM004035',
 'CPAYM004036',
 'CPAYM004037',
 'CPAYM004038',
 'CPAYM004039',
 'CPAYM004040',
 'CPAYM004041',
 'CPAYM004042',
 'CPAYM004043',
 'CPAYM004044',
 'CPAYM004045',
 'CPAYM004046',
 'CPAYM004047',
 'CPAYM004048',
 'CPAYM004049',
 'CPAYM004050',
 'CPAYM004051',
 'CPAYM004052',
 'CPAYM004053',
 'CPAYM004054',
 'CPAYM004055',
 'CPAYM004056',
 'CPAYM004057',
 'CPAYM004058',
 'CPAYM004059',
 'CPAYM004060',
 'CPAYM004061',
 'CPAYM004062',
 'CPAYM004063',
 'CPAYM004064',
 'CPAYM004065',
 'CPAYM004066',
 'CPAYM004067',
 'CPAYM004068',
 'CPAYM004069',
 'CPAYM004070',
 'CPAYM004071',
 'CPAYM004072',
 'CPAYM004073',
 'CPAYM004074',
 'CPAYM004075',
 'CPAYM004076',
 'CPAYM004077',
 'CPAYM004078',
 'CPAYM004079',
 'CPAYM004080',
 'CPAYM004081',
 'CPAYM004082',
 'CPAYM004083',
 'CPAYM004084',
 'CPAYM004085',
 'CPAYM004086',
 'CPAYM004087',
 'CPAYM004088',
 'CPAYM004089',
 'CPAYM004090',
 'CPAYM004091',
 'CPAYM004092',
 'CPAYM004093',
 'CPAYM004094',
 'CPAYM004095',
 'CPAYM004096',
 'CPAYM004097',
 'CPAYM004098',
 'CPAYM004099',
 'CPAYM004100',
 'CPAYM004101',
 'CPAYM004102',
 'CPAYM004103',
 'CPAYM004104',
 'CPAYM004105',
 'CPAYM004106',
 'CPAYM004107',
 'CPAYM004108',
 'CPAYM004109',
 'CPAYM004110',
 'CPAYM004111',
 'CPAYM004112',
 'CPAYM004113',
 'CPAYM004114',
 'CPAYM004115',
 'CPAYM004116',
 'CPAYM004117',
 'CPAYM004118',
 'CPAYM004119',
 'CPAYM004120',
 'CPAYM004121',
 'CPAYM004122',
 'CPAYM004123',
 'CPAYM004124',
 'CPAYM004125',
 'CPAYM004126',
 'CPAYM004127',
 'CPAYM004128',
 'CPAYM004129',
 'CPAYM004130',
 'CPAYM004131',
 'CPAYM004132',
 'CPAYM004133',
 'CPAYM004134',
 'CPAYM004135',
 'CPAYM004136',
 'CPAYM004137',
 'CPAYM004138',
 'CPAYM004139',
 'CPAYM004140',
 'CPAYM004141',
 'CPAYM004142',
 'CPAYM004143',
 'CPAYM004144',
 'CPAYM004145',
 'CPAYM004146',
 'CPAYM004147',
 'CPAYM004148',
 'CPAYM004149',
 'CPAYM004150',
 'CPAYM004151',
 'CPAYM004152',
 'CPAYM004153',
 'CPAYM004154',
 'CPAYM004155',
 'CPAYM004156',
 'CPAYM004157',
 'CPAYM004158',
 'CPAYM004159',
 'CPAYM004160',
 'CPAYM004161',
 'CPAYM004162',
 'CPAYM004163',
 'CPAYM004164',
 'CPAYM004165',
 'CPAYM004166',
 'CPAYM004167',
 'CPAYM004168',
 'CPAYM004169',
 'CPAYM004170',
 'CPAYM004171',
 'CPAYM004172',
 'CPAYM004173',
 'CPAYM004174',
 'CPAYM004175',
 'CPAYM004176',
 'CPAYM004177',
 'CPAYM004178',
 'CPAYM004179',
 'CPAYM004180',
 'CPAYM004181',
 'CPAYM004182',
 'CPAYM004183',
 'CPAYM004184',
 'CPAYM004185',
 'CPAYM004186',
 'CPAYM004187',
 'CPAYM004188',
 'CPAYM004189',
 'CPAYM004190',
 'CPAYM004191',
 'CPAYM004192',
 'CPAYM004193',
 'CPAYM004194',
 'CPAYM004195',
 'CPAYM004196',
 'CPAYM004197',
 'CPAYM004198',
 'CPAYM004199',
 'CPAYM004200',
 'CPAYM004201',
 'CPAYM004202',
 'CPAYM004203',
 'CPAYM004204',
 'CPAYM004205',
 'CPAYM004206',
 'CPAYM004207',
 'GLV150007455',
 'GLV150007471',
 'GLV150007479',
 'GLV150007480',
 'GLV150007481',
 'GLV150007482',
 'GLV150007483',
 'GLV150007484',
 'GLV150007485',
 'GLV150007486',
 'GLV150007487',
 'GLV150007488',
 'GLV150007494',
 'GLV150007495',
 'GLV150007496',
 'GLV150007498',
 'GLV150007501',
 'GLV150007502',
 'GLV150007503',
 'GLV150007504',
 'GLV150007505',
 'GLV150007506',
 'GLV150007507',
 'GLV150007508',
 'GLV150007519',
 'GLV150007520',
 'GLV150007521',
 'GLV150007522',
 'GLV150007523',
 'GLV150007529',
 'GLV150007530',
 'GLV150007547',
 'GLV150007548',
 'GLV150007549',
 'GLV150007550',
 'GLV150007551',
 'GLV150007552',
 'GLV150007553',
 'GLV150007560',
 'GLV150007561',
 'GLV150007562',
 'GLV150007563',
 'GLV150007564',
 'GLV150007565',
 'GLV150007566',
 'GLV150007567',
 'GLV150007568',
 'GLV150007569',
 'GLV150007571',
 'GLV150007580',
 'GLV150007581',
 'GLV150007582',
 'GLV150007603',
 'GLV150007604',
 'GLV150007605',
 'GLV150007606',
 'GLV150007622',
 'GLV150007623',
 'GLV150007624',
 'GLV150007627',
 'GLV150007628',
 'GLV150007629',
 'GLV150007630',
 'GLV150007631',
 'GLV150007632',
 'GLV150007633',
 'GLV150007635',
 'GLV150007636',
 'GLV150007637',
 'GLV150007638',
 'GLV150007644',
 'GLV150007645',
 'GLV150007646',
 'GLV150007655',
 'GLV150007656',
 'GLV150007677',
 'GLV150007678',
 'GLV150007681',
 'GLV150007682',
 'GLV150007683',
 'GLV150007684',
 'GLV150007685',
 'GLV150007686',
 'GLV150007687',
 'GLV150007688',
 'GLV150007689',
 'GLV150007690',
 'GLV150007691',
 'GLV150007692',
 'GLV150007693',
 'GLV150007694',
 'GLV150007695',
 'GLV150007696',
 'GLV150007697',
 'GLV150007698',
 'GLV150007699',
 'GLV150007700',
 'GLV150007701',
 'GLV150007711',
 'GLV150007712',
 'GLV150007734',
 'GLV150007739',
 'GLV150007740',
 'GLV150007741',
 'GLV150007742',
 'GLV150007744',
 'GLV150007745',
 'GLV150007746',
 'GLV150007747',
 'GLV150007748',
 'GLV150007749',
 'GLV150007756',
 'GLV150007761',
 'GLV150007762',
 'GLV150007763',
 'GLV150007764',
 'GLV150007765',
 'GLV150007766',
 'GLV150007767',
 'GLV150007768',
 'GLV150007769',
 'GLV150007770',
 'GLV150007775',
 'GLV150007778',
 'GLV150007779',
 'GLV150007780',
 'GLV150007807',
 'GLV150007808',
 'GLV150007809',
 'GLV150007810',
 'GLV150007811',
 'GLV150007812',
 'GLV150007816',
 'GLV150007817',
 'GLV150007818',
 'GLV150007819',
 'GLV150007820',
 'GLV150007821',
 'GLV150007822',
 'GLV150007835',
 'GLV150007836',
 'GLV150007837',
 'GLV150007838',
 'GLV150007846',
 'GLV150007847',
 'GLV150007848',
 'GLV150007849',
 'GLV150007850',
 'GLV150007851',
 'GLV150007852',
 'GLV150007853',
 'GLV150007854',
 'GLV150007855',
 'GLV150007856',
 'GLV150007857',
 'GLV150007858',
 'GLV150007859',
 'GLV150007862',
 'GLV150007867',
 'GLV150007868',
 'GLV150007871',
 'GLV150007872',
 'GLV150007873',
 'GLV150007874',
 'GLV150007875',
 'GLV150007876',
 'GLV150007877',
 'GLV150007878',
 'GLV150007879',
 'GLV150007880',
 'GLV150007881',
 'GLV150007882',
 'GLV150007883',
 'GLV150007886',
 'GLV150007887',
 'GLV150007888',
 'GLV150007889',
 'GLV150007890',
 'GLV150007918',
 'GLV150007919',
 'GLV150007920',
 'GLV150007921',
 'GLV150007922',
 'GLV150007923',
 'GLV150007924',
 'GLV150007925',
 'GLV150007926',
 'GLV150007927',
 'GLV150007928',
 'GLV150007930',
 'GLV150007931',
 'GLV150007932',
 'GLV150007933',
 'GLV150007934',
 'GLV150007935',
 'GLV150007936',
 'GLV150007937',
 'GLV150007938',
 'GLV150007939',
 'GLV150007940',
 'GLV150007941',
 'GLV150007942',
 'GLV150007943',
 'GLV150007944',
 'GLV150007945',
 'GLV150007946',
 'GLV150007947',
 'GLV150007948',
 'GLV150007949',
 'GLV150007951',
 'GLV150007952',
 'GLV150007953',
 'GLV150007980',
 'GLV150007981',
 'GLV150007982',
 'GLV150007983',
 'GLV150007984',
 'GLV150007985',
 'GLV150007986',
 'GLV150007989',
 'GLV150007990',
 'GLV150007991',
 'GLV150007992',
 'GLV150007995',
 'GLV150007996',
 'GLV150007997',
 'GLV150007998',
 'GLV150007999',
 'GLV150008000',
 'GLV150008001',
 'GLV150008002',
 'GLV150008003',
 'GLV150008009',
 'GLV150008010',
 'GLV150008011',
 'GLV150008018',
 'GLV150008019',
 'GLV150008020',
 'GLV150008021',
 'GLV150008026',
 'GLV150008027',
 'GLV150008028',
 'GLV150008029',
 'GLV150008030',
 'GLV150008031',
 'GLV150008032',
 'GLV150008033',
 'GLV150008034',
 'GLV150008035',
 'GLV150008036',
 'GLV150008037',
 'GLV150008038',
 'GLV150008039',
 'GLV150008040',
 'GLV150008042',
 'GLV150008043',
 'GLV150008044',
 'GLV150008045',
 'GLV150008046',
 'GLV150008047',
 'GLV150008048',
 'GLV150008049',
 'GLV150008050',
 'GLV150008051',
 'GLV150008052',
 'GLV150008055',
 'GLV150008056',
 'GLV150008057',
 'GLV150008058',
 'GLV150008059',
 'GLV150008060',
 'GLV150008061',
 'GLV150008063',
 'GLV150008064',
 'GLV150008065',
 'GLV150008066',
 'GLV150008067',
 'Open21b',
 'VPAYM007316',
 'VPAYM007317',
 'VPAYM007318',
 'VPAYM007319',
 'VPAYM007320',
 'VPAYM007321',
 'VPAYM007322',
 'VPAYM007323',
 'VPAYM007324',
 'VPAYM007325',
 'VPAYM007326',
 'VPAYM007327',
 'VPAYM007328',
 'VPAYM007329',
 'VPAYM007330',
 'VPAYM007331',
 'VPAYM007332',
 'VPAYM007333',
 'VPAYM007334',
 'VPAYM007335',
 'VPAYM007336',
 'VPAYM007337',
 'VPAYM007338',
 'VPAYM007339',
 'VPAYM007340',
 'VPAYM007341',
 'VPAYM007342',
 'VPAYM007343',
 'VPAYM007344',
 'VPAYM007345',
 'VPAYM007346',
 'VPAYM007347',
 'VPAYM007348',
 'VPAYM007349',
 'VPAYM007350',
 'VPAYM007351',
 'VPAYM007352',
 'VPAYM007353',
 'VPAYM007354',
 'VPAYM007355',
 'VPAYM007356',
 'VPAYM007357',
 'VPAYM007358',
 'VPAYM007359',
 'VPAYM007360',
 'VPAYM007361',
 'VPAYM007362',
 'VPAYM007363',
 'VPAYM007364',
 'VPAYM007365',
 'VPAYM007366',
 'VPAYM007367',
 'VPAYM007368',
 'VPAYM007369',
 'VPAYM007370',
 'VPAYM007371',
 'VPAYM007372',
 'VPAYM007373',
 'VPAYM007374',
 'VPAYM007375',
 'VPAYM007376',
 'VPAYM007377',
 'VPAYM007378',
 'VPAYM007379',
 'VPAYM007380',
 'VPAYM007381',
 'VPAYM007382',
 'VPAYM007383',
 'VPAYM007384',
 'VPAYM007385',
 'VPAYM007386',
 'VPAYM007387',
 'VPAYM007388',
 'VPAYM007389',
 'VPAYM007390',
 'VPAYM007391',
 'VPAYM007392',
 'VPAYM007393',
 'VPAYM007394',
 'VPAYM007395',
 'VPAYM007396',
 'VPAYM007397',
 'VPAYM007398',
 'VPAYM007399',
 'VPAYM007400',
 'VPAYM007401',
 'VPAYM007402',
 'VPAYM007403',
 'VPAYM007404',
 'VPAYM007405',
 'VPAYM007406',
 'VPAYM007407',
 'VPAYM007408',
 'VPAYM007409',
 'VPAYM007410',
 'VPAYM007411',
 'VPAYM007412',
 'VPAYM007413',
 'VPAYM007414',
 'VPAYM007415',
 'VPAYM007416',
 'VPAYM007417',
 'VPAYM007418',
 'VPAYM007419',
 'VPAYM007420',
 'VPAYM007421',
 'VPAYM007422',
 'VPAYM007423',
 'VPAYM007424',
 'VPAYM007425',
 'VPAYM007426',
 'VPAYM007427',
 'VPAYM007428',
 'VPAYM007429',
 'VPAYM007430',
 'VPAYM007431',
 'VPAYM007432',
 'VPAYM007433',
 'VPAYM007434',
 'VPAYM007435',
 'VPAYM007436',
 'VPAYM007437',
 'VPAYM007438',
 'VPAYM007439',
 'VPAYM007440',
 'VPAYM007441',
 'VPAYM007442',
 'VPAYM007443',
 'VPAYM007444',
 'VPAYM007445',
 'VPAYM007446',
 'VPAYM007447',
 'VPAYM007448',
 'VPAYM007449',
 'VPAYM007450',
 'VPAYM007451',
 'VPAYM007452',
 'VPAYM007453',
 'VPAYM007454',
 'VPAYM007455',
 'VPAYM007456',
 'VPAYM007457',
 'VPAYM007458',
 'VPAYM007459',
 'VPAYM007460',
 'VPAYM007461',
 'VPAYM007462',
 'VPAYM007463',
 'VPAYM007464',
 'VPAYM007465',
 'VPAYM007466',
 'VPAYM007467',
 'VPAYM007468',
 'VPAYM007469',
 'VPAYM007470',
 'VPAYM007471',
 'VPAYM007472',
 'VPAYM007473',
 'VPAYM007474',
 'VPAYM007475',
 'VPAYM007476',
 'VPAYM007477',
 'VPAYM007478',
 'VPAYM007479',
 'VPAYM007480',
 'VPAYM007481',
 'VPAYM007482',
 'VPAYM007483',
 'VPAYM007484',
 'VPAYM007485',
 'VPAYM007486',
 'VPAYM007487',
 'VPAYM007488',
 'VPAYM007489',
 'VPAYM007490',
 'VPAYM007491',
 'VPAYM007492',
 'VPAYM007493',
 'VPAYM007494',
 'VPAYM007495',
 'VPAYM007496',
 'VPAYM007497',
 'VPAYM007498',
 'VPAYM007499',
 'VPAYM007500',
 'VPAYM007501',
 'VPAYM007502',
 'VPAYM007503',
 'VPAYM007504',
 'VPAYM007505',
 'VPAYM007506',
 'VPAYM007507',
 'VPAYM007508',
 'VPAYM007509',
 'VPAYM007510',
 'VPAYM007511',
 'VPAYM007512',
 'VPAYM007513',
 'VPAYM007514',
 'VPAYM007515',
 'VPAYM007516',
 'VPAYM007517',
 'VPAYM007518',
 'VPAYM007519',
 'VPAYM007520',
 'VPAYM007521',
 'VPAYM007522',
 'VPAYM007523',
 'VPAYM007524',
 'VPAYM007525',
 'VPAYM007526',
 'VPAYM007527',
 'VPAYM007528',
 'VPAYM007529',
 'VPAYM007530',
 'VPAYM007531',
 'VPAYM007532',
 'VPAYM007533',
 'VPAYM007534',
 'VPAYM007535',
 'VPAYM007536',
 'VPAYM007537',
 'VPAYM007538',
 'VPAYM007539',
 'VPAYM007540',
 'VPAYM007541',
 'VPAYM007542',
 'VPAYM007543',
 'VPAYM007544',
 'VPAYM007545',
 'VPAYM007546',
 'VPAYM007547',
 'VPAYM007548',
 'VPAYM007549',
 'VPAYM007550',
 'VPAYM007551',
 'VPAYM007552',
 'VPAYM007553',
 'VPAYM007554',
 'VPAYM007555',
 'VPAYM007556',
 'VPAYM007557',
 'VPAYM007558',
 'VPAYM007559',
 'VPAYM007560',
 'VPAYM007561',
 'VPAYM007562',
 'VPAYM007563',
 'VPAYM007564',
 'VPAYM007565',
 'VPAYM007566',
 'VPAYM007567',
 'VPAYM007568',
 'VPAYM007569',
 'VPAYM007570',
 'VPAYM007571',
 'VPAYM007572',
 'VPAYM007573',
 'VPAYM007574',
 'VPAYM007575',
 'VPAYM007576',
 'VPAYM007577',
 'VPAYM007578',
 'VPAYM007579',
 'VPAYM007580',
 'VPAYM007581',
 'VPAYM007582',
 'VPAYM007583',
 'VPAYM007584',
 'VPAYM007585',
 'VPAYM007586',
 'VPAYM007587',
 'VPAYM007588',
 'VPAYM007589',
 'VPAYM007590',
 'VPAYM007591',
 'VPAYM007592',
 'VPAYM007593',
 'VPAYM007594',
 'VPAYM007595',
 'VPAYM007596',
 'VPAYM007597',
 'VPAYM007598',
 'VPAYM007599',
 'VPAYM007600',
 'VPAYM007601',
 'VPAYM007602',
 'VPAYM007603',
 'VPAYM007604',
 ...]

In [256]:
AllPreVouchers = set()
for i in PreVouchers:
    for j in i:
        AllPreVouchers.add(j)
AllPreVouchers = list(sorted(AllPreVouchers))
AllPreVouchers

['200-000005175',
 '200-000005200',
 '200-000005214',
 '200-000005221',
 '200-000005225',
 '200-000005271',
 '200-000005290',
 '200-000005291',
 '200-000005328',
 '200-000005335',
 '200-000005336',
 '200-000005337',
 '200-000005342',
 '200-000005343',
 '200-000005344',
 '200-000005391',
 '200-000005392',
 '200-000005450',
 '200-000005470',
 '200-000005474',
 '200-000005475',
 '200-000005481',
 '200-000005496',
 '200-000005503',
 '200-000005504',
 '200-000005508',
 '200-000005511',
 '200-000005516',
 '200-000005517',
 '200-000005518',
 '200-000005536',
 '200-000005539',
 '200-000005579',
 '200-000005591',
 '200-000005592',
 '200-000005629',
 '200-000005657',
 '200-000005674',
 '200-000005700',
 '200-000005703',
 '200-000005704',
 '200-000005711',
 '200-000005728',
 '200-000005731',
 '200-000005733',
 '200-000005744',
 '200-000005756',
 '200-000005763',
 '200-000005796',
 'GLV150007508',
 'GLV150007512',
 'GLV150007583',
 'GLV150007584',
 'GLV150007585',
 'GLV150007586',
 'GLV150007587',
 'GLV150007588',
 'GLV150007589',
 'GLV150007590',
 'GLV150007591',
 'GLV150007592',
 'GLV150007593',
 'GLV150007594',
 'GLV150007595',
 'GLV150007658',
 'GLV150007659',
 'GLV150007708',
 'GLV150007782',
 'GLV150007840',
 'GLV150007901',
 'GLV150007903',
 'GLV150007910',
 'GLV150007937',
 'GLV150007972',
 'GLV150008016',
 'GLV150008025',
 'Open21b']

In [297]:
AllAccrualVouchers = set()
for i in AccrualVouchers:
    for j in i:
        AllAccrualVouchers.add(j)
AllAccrualVouchers = list(sorted(AllAccrualVouchers))

In [298]:
AllAccrualVouchers

['200-000005264',
 '200-000005373',
 '200-000005468',
 '200-000005472',
 '200-000005662',
 '200-000005801',
 '200-000005820',
 '200-000005823',
 'ARFTIV000126',
 'GLV150007449',
 'GLV150007450',
 'GLV150007453',
 'GLV150007454',
 'GLV150007483',
 'GLV150007484',
 'GLV150007485',
 'GLV150007489',
 'GLV150007490',
 'GLV150007491',
 'GLV150007497',
 'GLV150007499',
 'GLV150007500',
 'GLV150007513',
 'GLV150007514',
 'GLV150007515',
 'GLV150007516',
 'GLV150007524',
 'GLV150007525',
 'GLV150007526',
 'GLV150007527',
 'GLV150007528',
 'GLV150007533',
 'GLV150007534',
 'GLV150007535',
 'GLV150007536',
 'GLV150007537',
 'GLV150007538',
 'GLV150007539',
 'GLV150007540',
 'GLV150007541',
 'GLV150007542',
 'GLV150007543',
 'GLV150007554',
 'GLV150007555',
 'GLV150007556',
 'GLV150007557',
 'GLV150007558',
 'GLV150007559',
 'GLV150007561',
 'GLV150007570',
 'GLV150007572',
 'GLV150007575',
 'GLV150007576',
 'GLV150007577',
 'GLV150007578',
 'GLV150007579',
 'GLV150007607',
 'GLV150007609',
 'GLV150007610',
 'GLV150007611',
 'GLV150007612',
 'GLV150007613',
 'GLV150007614',
 'GLV150007615',
 'GLV150007616',
 'GLV150007617',
 'GLV150007618',
 'GLV150007619',
 'GLV150007620',
 'GLV150007621',
 'GLV150007626',
 'GLV150007629',
 'GLV150007639',
 'GLV150007640',
 'GLV150007641',
 'GLV150007642',
 'GLV150007643',
 'GLV150007650',
 'GLV150007651',
 'GLV150007652',
 'GLV150007653',
 'GLV150007654',
 'GLV150007659',
 'GLV150007671',
 'GLV150007672',
 'GLV150007691',
 'GLV150007705',
 'GLV150007713',
 'GLV150007714',
 'GLV150007715',
 'GLV150007716',
 'GLV150007717',
 'GLV150007718',
 'GLV150007719',
 'GLV150007720',
 'GLV150007721',
 'GLV150007722',
 'GLV150007729',
 'GLV150007730',
 'GLV150007731',
 'GLV150007732',
 'GLV150007733',
 'GLV150007737',
 'GLV150007746',
 'GLV150007749',
 'GLV150007750',
 'GLV150007751',
 'GLV150007752',
 'GLV150007753',
 'GLV150007754',
 'GLV150007755',
 'GLV150007757',
 'GLV150007771',
 'GLV150007772',
 'GLV150007773',
 'GLV150007774',
 'GLV150007800',
 'GLV150007802',
 'GLV150007813',
 'GLV150007823',
 'GLV150007824',
 'GLV150007829',
 'GLV150007830',
 'GLV150007832',
 'GLV150007833',
 'GLV150007834',
 'GLV150007843',
 'GLV150007844',
 'GLV150007860',
 'GLV150007861',
 'GLV150007863',
 'GLV150007864',
 'GLV150007865',
 'GLV150007866',
 'GLV150007908',
 'GLV150007912',
 'GLV150007973',
 'GLV150007974',
 'GLV150008004',
 'GLV150008005',
 'GLV150008006',
 'GLV150008007',
 'GLV150008008',
 'GLV150008017',
 'GLV150008023',
 'GLV150008070',
 'GLV150008071',
 'GLV150008072',
 'GLV150008073',
 'GLV150008074',
 'GLV150008076',
 'GLV150008081',
 'Open21b']

In [299]:
BankVsPre = []
for i in AllBankVouchers:
    if i in AllPreVouchers:
        BankVsPre.append(i)

In [300]:
BankVsPre

['GLV150007508', 'GLV150007937', 'Open21b']

In [301]:
BankVsAccrual = []
for i in AllBankVouchers:
    if i in AllAccrualVouchers:
        BankVsAccrual.append(i)

In [302]:
BankVsAccrual

['GLV150007483',
 'GLV150007484',
 'GLV150007485',
 'GLV150007561',
 'GLV150007629',
 'GLV150007691',
 'GLV150007746',
 'GLV150007749',
 'Open21b']

In [304]:
BankFrame = df[df["Account Number"].isin(BankAcc)]
PreFrame = df[df["Account Number"].isin(PreAcc)]
AccrualFrame = df[df["Account Number"].isin(AccrualAcc)]

In [306]:
BankXPre = pd.concat([BankFrame,PreFrame])

In [307]:
BankXPre

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC),Amount,Months
58009,8525,BARCLAYS GBP ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8525,NaN,GBP,908654.93,0.00,908654.93,0.00,908654.93,0.00,908654.93,1
58010,8525,BARCLAYS GBP ACCOUNT,2021-01-05,200-135709,CPAYM003780,Bank,8525,BACS,GBP,1115.04,0.00,1115.04,0.00,1115.04,0.00,1115.04,1
58011,8525,BARCLAYS GBP ACCOUNT,2021-01-05,200-135710,CPAYM003781,Bank,8525,BACS,GBP,6919.00,0.00,6919.00,0.00,6919.00,0.00,6919.0,1
58012,8525,BARCLAYS GBP ACCOUNT,2021-01-05,200-135711,CPAYM003782,Bank,8525,BACS,GBP,30330.00,0.00,30330.00,0.00,30330.00,0.00,30330.0,1
58013,8525,BARCLAYS GBP ACCOUNT,2021-01-05,200-135712,VPAYM007316,Bank,8525,BACS,GBP,0.00,68.33,0.00,68.33,0.00,68.33,-68.33,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57957,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-09-30,200-147778,200-000005744,Ledger journal,8250,Security Information and Event Managment,USD,9012.20,0.00,6537.69,0.00,6537.69,0.00,6537.69,9
57958,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-09-30,200-147846,GLV150008016,Ledger journal,8250,Prepayments movement Sep,GBP,0.00,38870.43,0.00,38870.43,0.00,38870.43,-38870.43,9
57959,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-10-12,200-148273,200-000005763,Ledger journal,8250,Renewal insurance premium tax,GBP,12870.00,0.00,12870.00,0.00,12870.00,0.00,12870.0,10
57960,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-10-26,200-148852,200-000005796,Ledger journal,8250,IT back charge Q3 2021,USD,4821.87,0.00,3576.26,0.00,3576.26,0.00,3576.26,10
57961,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-10-31,200-149324,GLV150008025,Ledger journal,8250,Prepayments Oct 2021,GBP,0.00,45027.38,0.00,45027.38,0.00,45027.38,-45027.38,10

In [308]:
BankXPre = BankXPre[BankXPre["Voucher"].isin(BankVsPre)]

In [309]:
BankXPre

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC),Amount,Months
58009,8525,BARCLAYS GBP ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8525,NaN,GBP,908654.93,0.00,908654.93,0.0,908654.93,0.0,908654.93,1
59275,8525,BARCLAYS GBP ACCOUNT,2021-08-31,200-146009,GLV150007937,Bank,8525,Metlife,GBP,0.00,9986.00,0.00,9986.0,0.00,9986.0,-9986.0,8
59718,8526,BARCLAYS EURO ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8526,NaN,EUR,212097.57,0.00,183982.86,0.0,183982.86,0.0,183982.86,1
59720,8526,BARCLAYS EURO ACCOUNT,2021-01-28,200-136440,GLV150007508,Bank,8526,Helvetia,EUR,0.00,1453.76,0.00,1298.0,0.00,1298.0,-1298.0,1
59782,8527,BARCLAYS USD ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8527,NaN,USD,12.29,0.00,9.51,0.0,9.51,0.0,9.51,1
59795,8528,BARCLAYS CHF ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8528,NaN,CHF,12.46,0.00,9.73,0.0,9.73,0.0,9.73,1
57883,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-01-01,200-139439,Open21b,NaN,8250,NaN,EUR,1727.18,0.00,1392.78,0.0,1392.78,0.0,1392.78,1
57884,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-01-01,200-139439,Open21b,NaN,8250,NaN,GBP,81949.36,0.00,81949.36,0.0,81949.36,0.0,81949.36,1
57885,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-01-01,200-139439,Open21b,NaN,8250,NaN,USD,99800.63,0.00,79469.49,0.0,79469.49,0.0,79469.49,1
57888,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-01-28,200-136440,GLV150007508,Ledger journal,8250,Helvetia,EUR,1453.76,0.00,1298.00,0.0,1298.00,0.0,1298.0,1
57947,8250,SUNDRY DEBTORS & PREPAYMENTS,2021-08-31,200-146009,GLV150007937,Ledger journal,8250,Metlife,GBP,9986.00,0.00,9986.00,0.0,9986.00,0.0,9986.0,8

In [310]:
BankXAccrual = pd.concat([BankFrame,AccrualFrame])

In [311]:
BankXAccrual = BankXAccrual[BankXAccrual["Voucher"].isin(BankVsAccrual)]

In [312]:
BankXAccrual

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC),Amount,Months
58009,8525,BARCLAYS GBP ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8525,NaN,GBP,908654.93,0.00,908654.93,0.00,908654.93,0.00,908654.93,1
58076,8525,BARCLAYS GBP ACCOUNT,2021-01-15,200-136091,GLV150007483,Bank,8525,Pensions December 2020,GBP,11164.90,0.00,11164.90,0.00,11164.90,0.00,11164.9,1
58078,8525,BARCLAYS GBP ACCOUNT,2021-01-15,200-136093,GLV150007484,Bank,8525,Pensions December 2020 reversal,GBP,0.00,11164.90,0.00,11164.90,0.00,11164.90,-11164.9,1
58079,8525,BARCLAYS GBP ACCOUNT,2021-01-15,200-136094,GLV150007485,Bank,8525,December 2020 Pensions correction,GBP,0.00,11164.90,0.00,11164.90,0.00,11164.90,-11164.9,1
58232,8525,BARCLAYS GBP ACCOUNT,2021-02-15,200-137074,GLV150007561,Bank,8525,Pensions Jan 2021,GBP,0.00,14035.86,0.00,14035.86,0.00,14035.86,-14035.86,2
58340,8525,BARCLAYS GBP ACCOUNT,2021-03-15,200-138094,GLV150007629,Bank,8525,Pensions Feb 2021,GBP,0.00,12880.09,0.00,12880.09,0.00,12880.09,-12880.09,3
58506,8525,BARCLAYS GBP ACCOUNT,2021-04-15,200-139066,GLV150007691,Bank,8525,Pension,GBP,0.00,22264.01,0.00,22264.01,0.00,22264.01,-22264.01,4
58658,8525,BARCLAYS GBP ACCOUNT,2021-05-17,200-140417,GLV150007746,Bank,8525,Expenses,GBP,0.00,791.04,0.00,791.04,0.00,791.04,-791.04,5
58659,8525,BARCLAYS GBP ACCOUNT,2021-05-17,200-140417,GLV150007746,Bank,8525,Pension payment,GBP,0.00,8003.53,0.00,8003.53,0.00,8003.53,-8003.53,5
58663,8525,BARCLAYS GBP ACCOUNT,2021-05-17,200-140434,GLV150007749,Bank,8525,Pension payment,GBP,0.00,0.05,0.00,0.05,0.00,0.05,-0.05,5
59718,8526,BARCLAYS EURO ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8526,NaN,EUR,212097.57,0.00,183982.86,0.00,183982.86,0.00,183982.86,1
59782,8527,BARCLAYS USD ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8527,NaN,USD,12.29,0.00,9.51,0.00,9.51,0.00,9.51,1
59795,8528,BARCLAYS CHF ACCOUNT,2021-01-01,200-139439,Open21b,NaN,8528,NaN,CHF,12.46,0.00,9.73,0.00,9.73,0.00,9.73,1
66081,9201,SUNDRY CREDITORS & ACCRUALS,2021-01-01,200-139439,Open21b,NaN,9201,NaN,GBP,0.00,109458.87,0.00,109458.87,0.00,109458.87,-109458.87,1
66086,9201,SUNDRY CREDITORS & ACCRUALS,2021-01-15,200-136091,GLV150007483,Ledger journal,9201,Pensions December 2020,GBP,0.00,11164.90,0.00,11164.90,0.00,11164.90,-11164.9,1
66087,9201,SUNDRY CREDITORS & ACCRUALS,2021-01-15,200-136093,GLV150007484,Ledger journal,9201,Pensions December 2020 reversal,GBP,11164.90,0.00,11164.90,0.00,11164.90,0.00,11164.9,1
66088,9201,SUNDRY CREDITORS & ACCRUALS,2021-01-15,200-136094,GLV150007485,Ledger journal,9201,December 2020 Pensions correction,GBP,11164.90,0.00,11164.90,0.00,11164.90,0.00,11164.9,1
66104,9201,SUNDRY CREDITORS & ACCRUALS,2021-02-15,200-137074,GLV150007561,Ledger journal,9201,Pensions Jan 2021,GBP,14035.86,0.00,14035.86,0.00,14035.86,0.00,14035.86,2
66122,9201,SUNDRY CREDITORS & ACCRUALS,2021-03-15,200-138094,GLV150007629,Ledger journal,9201,Pensions Feb 2021,GBP,12880.09,0.00,12880.09,0.00,12880.09,0.00,12880.09,3
66128,9201,SUNDRY CREDITORS & ACCRUALS,2021-04-15,200-139066,GLV150007691,Ledger journal,9201,Pension,GBP,22264.01,0.00,22264.01,0.00,22264.01,0.00,22264.01,4
66137,9201,SUNDRY CREDITORS & ACCRUALS,2021-05-17,200-140417,GLV150007746,Ledger journal,9201,Pension payment,GBP,8003.53,0.00,8003.53,0.00,8003.53,0.00,8003.53,5
66138,9201,SUNDRY CREDITORS & ACCRUALS,2021-05-17,200-140434,GLV150007749,Ledger journal,9201,Pension payment,GBP,0.05,0.00,0.05,0.00,0.05,0.00,0.05,5
66159,9202,WARRANTY PROVISION,2021-01-01,200-139439,Open21b,NaN,9202,NaN,GBP,0.00,8500.00,0.00,8500.00,0.00,8500.00,-8500.0,1
66205,9206,INTER COMPANY ACCRUALS,2021-01-01,200-139439,Open21b,NaN,9206,NaN,CHF,0.00,0.00,122.53,0.00,122.53,0.00,122.53,1
66206,9206,INTER COMPANY ACCRUALS,2021-01-01,200-139439,Open21b,NaN,9206,NaN,EUR,0.00,14535.00,0.00,11947.19,0.00,11947.19,-11947.19,1
66207,9206,INTER COMPANY ACCRUALS,2021-01-01,200-139439,Open21b,NaN,9206,NaN,GBP,22555.32,0.00,22555.32,0.00,22555.32,0.00,22555.32,1
66208,9206,INTER COMPANY ACCRUALS,2021-01-01,200-139439,Open21b,NaN,9206,NaN,USD,1322.36,0.00,809.23,0.00,809.23,0.00,809.23,1
69327,9213,BONUS PROVISION 2018,2021-01-01,200-139439,Open21b,NaN,9213,NaN,GBP,0.00,51766.67,0.00,51766.67,0.00,51766.67,-51766.67,1

In [313]:
wb = load_workbook("Analysis.xlsx")
wr = pd.ExcelWriter("Analysis.xlsx", engine="openpyxl")
wr.book = wb
BankXPre.to_excel(wr,sheet_name="Bank Vs Prepayments", index = False)
wr.save()
wr.close()

In [314]:
wb = load_workbook("Analysis.xlsx")
wr = pd.ExcelWriter("Analysis.xlsx", engine="openpyxl")
wr.book = wb
BankXAccrual.to_excel(wr,sheet_name="Bank Vs Accrual", index = False)
wr.save()
wr.close()

In [316]:
PNLVouchers = df[df["Account Number"] == 6103] #PNL VOUCHER
PNLVouchers = PNLVouchers.groupby(["Account Number"])["Voucher"].agg("unique")
PNLVouchers
AllPNLVouchers = []
for i in PNLVouchers:
    for j in i:
        AllPNLVouchers.append(j)
AllPNLVouchers

['GLV150007710', 'GLV150007711']

In [317]:
BankVsPNL = []
for i in AllBankVouchers:
    if i in AllPNLVouchers:
        BankVsPNL.append(i)

In [318]:
BankVsPNL

['GLV150007711']

In [319]:
PNLFrame = df[df["Account Number"] == 6103]

In [320]:
BankXPNL = pd.concat([BankFrame,PNLFrame])

In [322]:
BankXPNL = BankXPNL[BankXPNL["Voucher"].isin(BankVsPNL)]

In [323]:
BankXPNL

,Account Number,Name,Date,Journal number,Voucher,Posting type,Ledger account,Description,Currency,Debit (TC),Credit (TC),Debit (AC),Credit (AC),Debit (RC),Credit (RC),Amount,Months
58584,8525,BARCLAYS GBP ACCOUNT,2021-04-30,200-139710,GLV150007711,Bank,8525,Car Value,GBP,6850.0,0.0,6850.0,0.0,6850.0,0.0,6850.0,4
88539,6103,PROFIT/(LOSS) OF ASSET SALE,2021-04-30,200-139710,GLV150007711,Ledger journal,6103-10800,Car Value,GBP,0.0,6850.0,0.0,6850.0,0.0,6850.0,-6850.0,4

In [324]:
wb = load_workbook("Analysis.xlsx")
wr = pd.ExcelWriter("Analysis.xlsx", engine="openpyxl")
wr.book = wb
BankXPNL.to_excel(wr,sheet_name="Bank Vs PNL", index = False)
wr.save()
wr.close()